author: Gaioli
database: false
description: Shout to your server
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.gaioli.plugins.ishout.Ishout
name: iShout
startup: postworld
version: '1.0'
